# -*- coding: utf-8 -*-
"""labwork1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGB1gJmjzTLFuy0HWJrL8PojY3NlK7AW
"""
# 1
r = float(input("Enter circle radius? "))
radius = r ** 2 * 3.14
print("Circle area = ", radius)
# 2
c = float(input("Enter the temparature in Celcius? "))
f = c * 9/5 + 32
print( c,"(C) = ", f , "(F)")
# 3
n = int(input("Enter a number? "))

if n <= 1:
   print(n, "is NOT a prime number")
else:
   prime = True

   for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
           prime = False
           break
   if prime:
        print(n, "is a prime number")
   else:
        print(n, "is NOT a prime number")
# 4
n = int(input("Enter a number? "))
s = 0

for i in range(1, n):
  if n % i == 0:
   s = s + i

if s == n:
  print(n,"is a perfect number")
else:
  print(n,"is not a perfect number")
# 5
colours = ["red", "blue", "green", "yellow", "purple"]

c = str(input("What is your favourite colour? "))
if c in colours:
  print("Your colour is at index", colours.index(c), "in my list")
else:
  print("Sorry, I could not find your colour")
# 6
range1 = list(range(0, 7, 1))
range2 = list(range(1, 11, 3))
range3 = list(range(5, 0, -1))
range4 = list(range(6, -3, -2))

print(range1)
print(range2)
print(range3)
print(range4)
# 7
def remove_dollar_sign(s):
  return s.replace("$", "")
n = str(input("Enter a string;: "))

print(remove_dollar_sign(n))
# 8
l = [1, 4, 5, -1, 10]

def extract_even(c):
  return [x for x in c if x % 2 == 0]

print(extract_even(l))
# 9
def factorial(c):
  if c < 0:
    return "Input must be a non-negative integer."
  else:
    result = 1
    for i in range(1, c + 1):
      result = result * i
    return result

l = int(input("Enter a number: "))
print(factorial(l))
# 10
def function(c):
  divisors = []
  for i in range(1, c + 1):
    if c % i == 0:
      divisors += [i]
  return divisors

l = int(input("Enter a number: "))
print(function(l))
# 11
import math

def calculate(x1, x2, y1, y2):
  return math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

p1x = float(input("Enter x1: "))
p2x = float(input("Enter x2: "))
p1y = float(input("Enter y1: "))
p2y = float(input("Enter y2: "))

distance = calculate(p1x, p2x, p1y, p2y)
print(f"Distance: {distance}")
# 12
m = int(input("Input m "))
n = int(input("Input n "))
for i in range(m):
  s = ""
  for j in range(n):
    if i == 0 or i == m - 1 or j == 0 or j == n - 1:
      s += "* "
    else:
      s += "  "
  print(s)